package com.and.movies.data.repo.movie;

import com.google.gson.TypeAdapterFactory;
import com.ryanharter.auto.value.gson.GsonTypeAdapterFactory;

/**
 * TypeAdapterFactory for register type adapters of all classes were generated by auto-value-gson
 */
@GsonTypeAdapterFactory
public abstract class DataLayerAdapterFactory implements TypeAdapterFactory {

    public static TypeAdapterFactory create() {
        return new AutoValueGson_DataLayerAdapterFactory();
    }
}
